version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    container_name: snipeit_nginx
    ports:
      - "80:80"
    volumes:
      - ./../:/usr/share/nginx/html:rw
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
    depends_on:
      - snipeit
    networks:
      snipeit-backend:
        aliases:
          - nginx

  snipeit:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile
    image: snipeit:v5
    container_name: snipeit
    volumes:
      - ./../:/usr/share/nginx/html:rw
      - ./configs/.env:/usr/share/nginx/html/.env:ro
      - ./configs/php/php.ini-production:/usr/local/etc/php/php.ini:ro
      - snipe_data:/var/lib/snipeit
    networks:
      snipeit-backend:
        aliases:
          - snipeit
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:10.6.4-focal
    container_name: snipeit_mariadb
    volumes:
      - snipe_mysql_db:/var/lib/mysql
      - ./configs/mariadb/mariadb.cnf:/etc/mysql/conf.d/custom-configs.cnf
      - ./configs/mariadb/ssl:/etc/mysql/ssl
    env_file:
      - configs/mariadb/mariadb.env
    networks:
      snipeit-backend:
        aliases:
          - mariadb

  redis:
    image: redis:6.2.5-buster
    container_name: snipeit_redis
    networks:
      snipeit-backend:
        aliases:
          - redis

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: snipeit_mailhog
    ports:
      - "8025:8025"
    networks:
      snipeit-backend:
        aliases:
          - mailhog

volumes:
  snipe_data:
  snipe_mysql_db:

networks:
  snipeit-backend: